### ISSUE TITLE
Incoming __ow_headers are not transferred to static actions

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-dispatch#192]
While working on https://github.com/adobe/openwhisk-action-logger/issues/3, I realised that the incoming `__ow_headers` are not transferred to the static action. 

I am not sure if this is a design choice or just that we never needed them before.

@trieloff Idea ?

**Comment by tripodsan** [comment]
why do the static actions need the params ?

**Comment by kptdobe** [comment]
In my case, they need the `__ow_headers` which are stored in the params.

**Comment by kptdobe** [comment]
Also, for the "content" actions, we transfer the params with no filtering: https://github.com/adobe/helix-dispatch/blob/master/src/fetchers.js#L377

**Comment by trieloff** [comment]
That's an omission. The fix in #193 is a good idea.

**Comment by kptdobe** [comment]
Now that I start understanding the code, I need to change the fix :). Too many `params` :)

**Comment by kptdobe** [comment]
I got confused with the `params` property which is used too often `params: params.params` and new params being recomputed by merging objects.

Here is what the PR does: just propagate the `wskOpts` (`__ow_headers` and `__ow_logger`) to the static action calls (like for the content action calls). I also added the corresponding test to validate that headers are propagated to all the fetchers.

**Comment by tripodsan** [comment]
> Also, for the "content" actions, we transfer the params with no filtering: https://github.com/adobe/helix-dispatch/blob/master/src/fetchers.js#L377

yes, but those are the `params` needed for the pipeline action, originating from the VCL. those are not the action params sent to the disaptcher.

**Comment by kptdobe** [comment]
Yes, took me a while to understand that. As I said too many `params` ;)
