### ISSUE TITLE
Vanity URL Resolution

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-dispatch#204]
Idea: at the same time as the normal invocations are running, look up lib-aio-state if a vanity URL has been registered. If no (in most cases) just proceed. If yes, restart the resolution with the new path.

As long as lib-aio-state is not slower than a runtime invocation itself, this should have negligible performance impact.

**Comment by trieloff** [comment]
@dominique-pfister are we using lib-aio-state somewhere else? Is there a risk of collisions for the key names?

**Comment by trieloff** [comment]
In any case, we should probably use a proper prefix like `vanity:https://theblog.adobe.com/mybrandnewpost` as the URL and `/posts/en/2020/welcome-to-summit.html` as the value. 

This way, vanity URLs can only affect the path, i.e. they won't be able to override `repo`, `owner` or `ref`.

In Helix Pages in particular, you would be able to define vanity URLs for someone else's pages and I'm not sure yet how to prevent that.

Imagine we have an index config that watches for `/^Available at: (https://.*)$` in the content and use this to use whatever is in `$1` as the key and the actual content path as the value. You could easily enter someone else's domain name and would effectively establish a redirect for them.

One possible solution would be to discard the user specified hostname and always use the hostname that the indexer is using to fetch the content from.

**Comment by dominique-pfister** [comment]
> are we using lib-aio-state somewhere else? Is there a risk of collisions for the key names?
In `helix-onedrive-listener` but not merged to master yet: the key used has the format `<owner>--<repo>--<ref>`, but we could still prefix this with a package and/or action name.

**Comment by dominique-pfister** [comment]
I'm wondering: where and how are those vanity URLs configured, not in `lib-aio-state` only, I presume?

**Comment by trieloff** [comment]
> I'm wondering: where and how are those vanity URLs configured, not in `lib-aio-state` only, I presume?

I would think that we would build either

a) another bot/listener to update the vanity URLs from content/HTML
b) extend the existing indexer to do so

For regular helix sites, I'd say that the correct way to do this would be to look for `<link rel="canonical" href="…">` in the HTML. For Helix Pages, a configuration that is close to the index config would feel natural.

**Comment by trieloff** [comment]
Speaking of the key format: what about:

`<action-name>:<owner>--<repo>--<ref>:` as the prefix?

**Comment by tripodsan** [comment]
addressed in new redirect feature.
