### ISSUE TITLE
invalid 500 for invalid paths

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-dispatch#320]
`/api/v1/web/helix-pages/helix-services/dispatch@v4?static.owner=adobe&static.repo=helix-pages&static.ref=master&static.root=/htdocs&content.owner=adobe&content.repo=theblog&content.ref=master&content.root=&content.package=4febca0941fe75e78d2da140aa1f93d95700fd8c&content.index=index.html&path=/how-covid-19-is-impacting-online-shopping-behavior%2&strain=default&rootPath=&params=` yields 500, should be 400

**Comment by stefan-guggisberg** [comment]
you beat me to it :)

**Comment by dominique-pfister** [comment]
I don't think this is related to dispatch. I can enter whatever action, even in the browser:
```
https://adobeioruntime.net/api/v1/namespaces/dpfister/actions/gurk?blocking=true&result=true&path=/%2
```
gives me the same error 😆

**Comment by stefan-guggisberg** [comment]
it's thrown by Scala code => I/O Runtime :)

https://doc.akka.io/docs/akka-http/current/common/uri-model.html

**Comment by trieloff** [comment]
we could still clean this in helix-publish
