### ISSUE TITLE
Epsagon is reporting OutOfMemory

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-dispatch#508]
Starting 14 Jul, Epsagon repeatedly reports that this Lambda uses all of its 512 MB, potentially running into an OutOfMemory error:

https://app.epsagon.com/functions/118435662149/us-east-1/helix-services--dispatch?filters%5Bstatus%5D%5B0%5D=out_of_memory

**Comment by tripodsan** [comment]
let's deploy then to force a coldstart

**Comment by tripodsan** [comment]
the chart als looks like a memory leak:

![image](https://user-images.githubusercontent.com/917628/125780988-f7e4e425-b3d6-41ad-9c50-da2e76782c07.png)

**Comment by dominique-pfister** [comment]
does "als" mean rather yes or no?
