### ISSUE TITLE
Process ESI

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-dispatch#6]
Process ESI here instead of Fastly, so that we can make use of compression (and advanced ESI features like fallbacks)

**Comment by tripodsan** [comment]
how would you handle the case, when the ESI processed content gets too large for an openwhisk response?

**Comment by trieloff** [comment]
Good question. One strategy might be to offload the prospective response into an S3 bucket, and then use the `X-Location` feature in Fastly to deliver from the S3 bucket.

**Comment by trieloff** [comment]
Additional open question: 

With ESI handled on the edge, there is no issue of cache integrity, as the ESI will be processed in each request, and the fragments loaded from cache or origin. With ESI processed in Runtime, cache invalidations won't be passed through unless we provide a way of concatenating the `Surrogate-Keys`

**Comment by trieloff** [comment]
We should not do this.
